### PR TITLE
Endgame balance

### PR DESCRIPTION
**Pull request by palmdrop**
Balance weights, change aggression and search behaviors. From my observations, stalemates does not occur anymore. The pace of the game is also increased a bit.

### CODE REVIEW

**Comment by feldtsen** [comment]
I did not experience any stalemates, but more people should do a test run.

**Review by feldtsen — COMMENTED** [review]
I did not experience any stalemates, but more people should do a test run.

**Comment by frans-bergman** [comment]
image
Still seeing weird stuff when only 1 unit is left, but otherwise looks better.

**Comment by palmdrop** [comment]
> image
> Still seeing weird stuff when only 1 unit is left, but otherwise looks better.

Will try to fix that, however happens quite rarely. Might be worth merging and fixing this issue in another PR.

**Review by frans-bergman — APPROVED** [review]
Should have approved yesterday. Works better than current main.

**Pull request merged**
