### PR TITLE
Selection improvements

### PR DESCRIPTION
**Pull request by feldtsen**
Observed bugs that still need to get fixed:
- The problem with the selections sphere disappearing is still present.
- Boids can still spawn at different heights.

### CODE REVIEW

**Comment by Jononannes** [comment]
The second bug you mention does not seem related to the selection itself, since when the boids are selected and moved they end up at the correct height. I agree that it should be fixed, though.

As for the bug about disappearing selection spheres, that is definitely connected to the selection, and should be fixed in this pr.

**Comment by feldtsen** [comment]
@VidarHook found a better solution. Therefore, I will not fix the selection sphere bug.

**Comment by Jononannes** [comment]
I can't run dusk in multiplayer on this branch. Unity says there are merge conflicts in Dusk.unity.

**Comment by feldtsen** [comment]
Does it look alright now, @Jononannes?

**Review by Jononannes — APPROVED** [review]
Yes, it looks good now!

**Pull request merged**
