### PR TITLE
Behavior changes to avoid stalemates and boids doing nothing when attacked from behind

### PR DESCRIPTION
**Pull request by palmdrop**

### CODE REVIEW

**Comment by Jononannes** [comment]
It looks like the boids are turning away when being attacked from behind now, and they don't spin around eachother, so nicely done.

However, when a large flock is about to win, it tends to ignore the smaller enemy flock in favour of sticking together (the alignment behaviour is possibly too strong compared to the aggression force because of the small amount of enemies). This results in battles taking a long time to finish, and since this pr aims to avoid stalemates, this should probably be fixed.

**Comment by palmdrop** [comment]
> It looks like the boids are turning away when being attacked from behind now, and they don't spin around eachother, so nicely done.
> 
> However, when a large flock is about to win, it tends to ignore the smaller enemy flock in favour of sticking together (the alignment behaviour is possibly too strong compared to the aggression force because of the small amount of enemies). This results in battles taking a long time to finish, and since this pr aims to avoid stalemates, this should probably be fixed.

Agree, although that has been a problem for a long time. One possible solution might be to scale the aggression depending on the relationship between the sizes of the opposing flocks. I'll try that, however, a more complex map might solve the problem as well.

**Comment by frans-bergman** [comment]
Would it be possible for you to cherry pick your commits on top of main to get rid of the merge commits?

**Comment by palmdrop** [comment]
> Would it be possible for you to cherry pick your commits on top of main to get rid of the merge commits?

Not sure how I would do that, however I understand that I should probably not merge with main as often. I will try to produce a more clean commit history in the future.

**Comment by frans-bergman** [comment]
> > Would it be possible for you to cherry pick your commits on top of main to get rid of the merge commits?
> 
> Not sure how I would do that, however I understand that I should probably not merge with main as often. I will try to produce a more clean commit history in the future.

```
git checkout main
git checkout -b my-clean-branch
git cherry-pick 57897cf
git cherry-pick 289dd72
git cherry-pick ...
...
git push --set-upstream origin my-clean-branch
```

**Pull request closed without merging**
