### PR TITLE
Add pause menu

### PR DESCRIPTION
**Pull request by frans-bergman**

### CODE REVIEW

**Comment by Jononannes** [comment]
I found a few issues:
- When boids are close together, pausing and resuming makes them explode outwards from eachother.
- The battle music keeps playing when going to the main menu. It can be stopped by calling `AudioManager.instance.StopMusic("BattleMusic");` whenever you click the menu button.
- When paused, you can still rotate the camera, but the effects take place only after resuming.
- The selection rectangle is appearing when paused, but it probably shouldn't be there after starting the battle anyway.

The last two aren't big issues, so fix them if you want. Though the first two should probably be fixed to not impact the game experience.

**Comment by frans-bergman** [comment]
Issue 2 and 3 are fixed now. I can't reproduce issue 1. Issue 4 should be fixed by only enabling the selection tool at appropriate times.

**Comment by frans-bergman** [comment]
I actually could reproduce issue 1. Removing the timeScale change for now, will work on that in a separate PR.

**Review by ahanton — APPROVED** [review]
Great! Approved since you will implement the time scaling and fix issue 1 in a seperate PR and because I need this in order to work on prettifying the UI.

**Review by Jononannes — APPROVED** [review]
Alright, looks good now.

**Pull request merged**
